title: yutkat
description: yutkat's website
logo: https://avatars.githubusercontent.com/u/8683947
show_downloads: false
plugins:
- jekyll-sitemap
- jekyll-remote-theme 
google_analytics: G-LFN9ZWJFXX
remote_theme: "godalming123/minimal"
#theme: jekyll-theme-minimal
include: [".well-known"]
